# Global Travis CI step definitions that will be used by all jobs unless
# explicitly overriden in the jobs.include matrix.

language: python
python: "3.6"

services:
  - postgresql
  - redis-server

addons:
  postgresql: "9.4"

install: pip install tox

script: tox -e $TOX_ENV

# Build stages.
jobs:
  include:
    - stage: test
      env:
        - TOX_ENV=py36
        # Set environment variables with information how to use the required
        # services.
        - DRFR_POSTGRESQL_USER=postgres
        - DRFR_POSTGRESQL_PORT=5432
        - DRFR_REDIS_PORT=6379

    # NOTE: We undo almost all global Travis CI step definitions to ensure the
    # following Tox environments are run without access to any service.
    - stage: test
      env: TOX_ENV=packaging
      services: []
      addons: {}

    # NOTE: We undo many global Travis CI step definitions to ensure the
    # following Tox environment only has access to the PostgreSQL service.
    - stage: test
      env:
        - TOX_ENV=migrations
        # Set environment variables with information how to use the PostgreSQL
        # service.
        - DRFR_POSTGRESQL_USER=postgres
        - DRFR_POSTGRESQL_PORT=5432
      services:
        - postgresql
