# Global Travis CI step definitions that will be used by all jobs unless
# explicitly overriden in the jobs.include matrix.

language: python
# We need to be able to install packages.
sudo: required
python: "3.6"

services:
  - redis-server

addons:
  # NOTE: We need to use the postgresql addon since the default PostgreSQL
  # service provided on Trusty machines is PostgreSQL 9.2.
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_install:
  # NOTE: We need to manually reconfigure PostgreSQL 10 since Travis CI doesn't
  # provide standard configuration out-of-the-box.
  # For more details, see:
  # https://github.com/travis-ci/travis-ci/issues/8537#issuecomment-416467506
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo service postgresql restart

install: pip install tox

script: tox -e $TOX_ENV

# Build stages.
jobs:
  include:
    - stage: test
      env:
        - TOX_ENV=py36
        # Set environment variables with information how to use the required
        # services.
        - DRFR_POSTGRESQL_USER=postgres
        - DRFR_POSTGRESQL_PORT=5432
        - DRFR_REDIS_PORT=6379

    # NOTE: We undo almost all global Travis CI step definitions to ensure the
    # following Tox environments are run without access to any service.
    - stage: test
      env: TOX_ENV=packaging
      services: []
      addons: {}
      before_install: skip

    # NOTE: We undo many global Travis CI step definitions to ensure the
    # following Tox environment only has access to the PostgreSQL service.
    - stage: test
      env:
        - TOX_ENV=migrations
        # Set environment variables with information how to use the PostgreSQL
        # service.
        - DRFR_POSTGRESQL_USER=postgres
        - DRFR_POSTGRESQL_PORT=5432
      services:
        - postgresql
