sudo: required

# NOTE: It is necessary to explicitly set the distribution to "trusty" due to
# the complex 'matrix: include:' logic below
# More information: https://github.com/travis-ci/travis-ci/issues/5448
dist: trusty

addons:
  postgresql: "9.4"

services:
  - postgresql
  - redis-server

language: python

env:
  global:
    - DRFR_POSTGRESQL_USER=postgres
    - DRFR_POSTGRESQL_PORT=5432
    - DRFR_REDIS_PORT=6379

# NOTE: Explicit Python versions make Travis job description more informative
matrix:
  include:
    - env: TOX_ENV=py27
      python: "2.7"
    - env: TOX_ENV=py34
      python: "3.4"
    - env: TOX_ENV=py35
      python: "3.5"

install: pip install tox

script: tox -e $TOX_ENV
